config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :users do
    resources :galleries
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :user
  # validates_presence_of :photo
  mount_uploader :photo, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_gallery, only: [:edit, :update, :destroy, :show]

    def index
      @galleries = Gallery.where(user_id: params[:user_id])
    end
    
    def new
      @gallery = Gallery.new
    end
    
    def create
      @gallery = Gallery.new(gallery_params)
      @gallery.user = current_user

      if @gallery.valid? && @gallery.save
        redirect_to user_galleries_path(current_user)
      else
        if @gallery.photo.url == nil
          redirect_back fallback_location: root_path, notice: "ERROR: 無選取相片"
        else
          redirect_back fallback_location: root_path, notice: "ERROR: 上傳失敗!"
        end
      end
    end

    def edit

    end

    def update
      if @gallery.update(gallery_params)
        redirect_to user_galleries_path(current_user), notice: "更新成功!"
      else
        redirect_back fallback_location: root_path, notice: "ERROR: 更新失敗!"
      end
    end
    
    def show
    end
    
    def destroy
      if @gallery.destroy
        @gallery.remove_photo!
        redirect_to user_galleries_path(current_user), notice: "刪除成功!"
      else
        redirect_back fallback_location: root_path, notice: "ERROR: 刪除失敗!"
      end
    end

    private
    def gallery_params
      @gallery = params.require(:gallery).permit(:title, :description, :photo)
    end

    def find_gallery
      @gallery = Gallery.find_by(id: params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


    def index
      @news = Gallery.order(created_at: :desc).first(20)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>
         #{pluralize(resource.errors.count, 'error')} must be fixed
        </strong>
        #{messages}
      </div>
      HTML

    html.html_safe
  end
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/galleries/_form.html.erb
<p class="mg-lg">
    <h1><%= page_title %></h1>
</p>
<%= form_for gallery, url: gpath do |f| %>
    <div class="row">
        <div class="col-sm-6">
            <%= f.label :title, "標題", for:"upload_title" %>
            <p class="mg-lg">
                <%= f.text_field :title, class:"form-control", id:"upload_title", placeholder:"Title" %>
            </p>
            <%= f.label :description, "描述", for:"Descripe" %>
            <p class="mg-lg">
                <%= f.text_area :description, class:"form-control", rows:"5", id:"Descripe", placeholder:"Descripe" %>
            </p>
            <div class="form-group">
                <%= f.label :photo, "相片" %>
                <%= f.file_field :photo, class:"form-control-file", onchange: "readURL(this);", id:"upload_image" %>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label for="Preview">預覽</label>
                <p class="mg-lg">
                    <% if gallery.photo.url %>
                    <%= image_tag gallery.photo, class:"img-responsive center-block", id:"preview" %>
                    <% else %>
                    <%= image_tag "placeholder-image.png", class:"img-responsive center-block", id:"preview" %>
                    <% end %>
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-6">
            <div class="text-right marginButton">
                <%= f.submit submit_title, class:"btn btn-d btn-lg" %>
                <% if gallery.photo.url %>
                <%= link_to "刪除", user_gallery_path(id: gallery.id), method: "Delete", class:"btn btn-danger btn-d btn-lg", data: { confirm: "Are you sure?" } %>
                <% end %>
            </div>
        </div>
    </div>       
<% end %>
        

app/views/galleries/_gallery_view.html.erb
<div class="row">
        <div class="col-sm-12">
            <h2 class="text-center mg-md">
                <%= title %>
            </h2>
            <p class="text-center sub-heading">
                
            </p>
        </div>
    </div>
    <%= galleries.each_slice 4 do |a, b, c, d| %>
    <div class="row voffset">
        <% if a %>
            <div class="col-sm-3">
                <!-- <a href="#" data-lightbox="<%= a.photo.url %>" data-caption="<%= a.description %>" data-gallery-id="gallery-1"><img src="<%= a.photo.medium.url %>" class="img-responsive" /></a> -->
                <%= link_to  (image_tag a.photo.medium.url, class: "img-responsive" ), "#", "data-lightbox": a.photo.url, "data-caption": a.description, "data-gallery-id": "gallery-1" %>
                <div class="text-center">
                    <%= link_to a.title, current_user == a.user ? edit_user_gallery_path(id: a.id, user_id: a.user.id) : user_gallery_path(id: a.id, user_id: a.user.id), class:"btn btn-block btn-sq btn-d" %>
                </div>
            </div>
        <% else %>
            <div class="col-sm-3">
            <%= link_to  (image_tag "placeholder-image-sq.png", class: "img-responsive"), new_user_gallery_path(:user) %>
            <div class="text-center">
                <%= link_to "新相片", new_user_gallery_path(:user), class:"btn btn-block btn-sq btn-d" %>
            </div>
            </div>
        <% end %>
        <% if b %>
            <div class="col-sm-3">
                <a href="#" data-lightbox="<%= b.photo.url %>" data-caption="<%= b.description %>" data-gallery-id="gallery-1"><img src="<%= b.photo.medium.url %>" class="img-responsive" /></a>
                <div class="text-center">
                    <%= link_to b.title, current_user == b.user ? edit_user_gallery_path(id: b.id, user_id: b.user.id) : user_gallery_path(id: b.id, user_id: b.user.id), class:"btn btn-block btn-sq btn-d" %>
                </div>
            </div>
        <% elsif a %>
            <div class="col-sm-3">
            <%= link_to  (image_tag "placeholder-image-sq.png", class: "img-responsive"), new_user_gallery_path(:user) %>
            <div class="text-center">
                <%= link_to "新相片", new_user_gallery_path(:user), class:"btn btn-block btn-sq btn-d" %>
            </div>
            </div>
        <% end %>
        <% if c %>
            <div class="col-sm-3">
                <a href="#" data-lightbox="<%= c.photo.url %>" data-caption="<%= c.description %>" data-gallery-id="gallery-1"><img src="<%= c.photo.medium.url %>" class="img-responsive" /></a>
                <div class="text-center">
                    <%= link_to c.title, current_user == c.user ? edit_user_gallery_path(id: c.id, user_id: c.user.id) : user_gallery_path(id: c.id, user_id: c.user.id), class:"btn btn-block btn-sq btn-d" %>
                </div>
            </div>
            <% elsif b %>
            <div class="col-sm-3">
                <%= link_to  (image_tag "placeholder-image-sq.png", class: "img-responsive"), new_user_gallery_path(:user) %>
            <div class="text-center">
                <%= link_to"新相片", new_user_gallery_path(:user), class:"btn btn-block btn-sq btn-d" %>
            </div>    
            </div>
        <% end %>
        <% if d %>
            <div class="col-sm-3">
                <a href="#" data-lightbox="<%= d.photo.url %>" data-caption="<%= d.description %>" data-gallery-id="gallery-1"><img src="<%= d.photo.medium.url %>" class="img-responsive" /></a>
                <div class="text-center">
                    <%= link_to d.title, current_user == d.user ? edit_user_gallery_path(id: d.id, user_id: d.user.id) : user_gallery_path(id: d.id, user_id: d.user.id), class:"btn btn-block btn-sq btn-d" %>
                </div>
            </div>
        <% elsif c %>
        <div class="col-sm-3">
            <%= link_to  (image_tag "placeholder-image-sq.png", class: "img-responsive"), new_user_gallery_path(:user) %>
            <div class="text-center">
                <%= link_to "新相片", new_user_gallery_path(:user), class:"btn btn-block btn-sq btn-d" %>
            </div>
        </div>
        <% end %>
    </div>
    <% end  %>
    <% if galleries.count % 4 == 0 %>
    <div class="row voffset">
        <div class="col-sm-3">
            <%= link_to  (image_tag "placeholder-image-sq.png", class: "img-responsive"), new_user_gallery_path(:user) %>
            <div class="text-center">
                <%= link_to "新相片", new_user_gallery_path(:user), class:"btn btn-block btn-sq btn-d" %>
            </div>
        </div>
    </div>
<% end %>
<style>
    .col-sm-3 > .btn{
        border-radius: 0;
    }
    .col-sm-3 > div.text-center{
        background-color: #47454b;
    }
    .col-sm-3 > .btn{
        transition: 0.5s;
    }
    .col-sm-3:hover .btn{
        color: #cac5c0 !important;
    }
</style>

app/views/galleries/edit.html.erb
<!-- bloc-10 -->
<div class="bloc l-bloc bgc-white" id="bloc-10">
        <div class="container bloc-lg">
            <% if notice && notice.include?("ERROR") %>
            <%= "<div class='alert alert-danger' role:'alert'>#{notice}</div>".html_safe %>
            <% end %>
            <%= render "form", gallery: @gallery, page_title: "Edit", submit_title: "更新", gpath: user_gallery_path %>
        </div>
</div>
<!-- bloc-10 END -->

app/views/galleries/index.html.erb
<!-- bloc-3 -->
<div class="bloc l-bloc bgc-white" id="bloc-3">
        <div class="container bloc-lg">
            <%= render  "gallery_view", galleries: @galleries, title: "藝廊" %>
        </div>
</div>
<!-- bloc-3 END -->

app/views/galleries/new.html.erb
<!-- bloc-2 -->
<div class="bloc l-bloc bgc-white" id="bloc-2">
    <div class="container bloc-lg">
        <%= render "form", gallery: @gallery, page_title: "上傳", submit_title: "建立", gpath: user_galleries_path %>
    </div>
</div>
<!-- bloc-2 END -->

app/views/galleries/show.html.erb
<!-- bloc-11 -->
<div class="bloc l-bloc bgc-white" id="bloc-11">
    <div class="container bloc-lg">
        <div class="row">
                <div class="col-sm-6">
                    <%= image_tag  @gallery.photo ? @gallery.photo : "placeholder-image.png", class:"img-responsive" %>
                </div>
                <div class="col-sm-6">
                    <h2 class="mg-sm">
                        <%= @gallery.title %>
                    </h2>
                    <p style="font-size: 12px">
                        <%= "#{@gallery.user.nickname}, #{@gallery.created_at.strftime("%Y-%m-%d")}" %>
                    </p>
                    <p class="mg-lg" style="font-size: 18px">
                        <%= @gallery.description %>
                    </p>
                    <p class="mg-sm">
                        <%= link_to  "想看更多？", user_galleries_path(@gallery.user.id), class:"btn btn-d" %>
                    </p>
                </div>
        </div>
    </div>
</div>
<!-- bloc-11 END -->

app/views/gallery/index.html.erb
<!-- bloc-3 -->
<div class="bloc l-bloc bgc-white" id="bloc-3">
        <div class="container bloc-lg">
            <div class="row">
                <div class="col-sm-12">
                    <h2 class="text-center mg-md">
                        Gallery
                    </h2>
                    <p class="text-center sub-heading">
                        Just a sample of what we do.
                    </p>
                </div>
            </div>
            <div class="row voffset">
                <div class="col-sm-3">
                    <a href="#" data-lightbox="img/placeholder-image.png" data-caption="Image description" data-gallery-id="gallery-1"><img src="img/placeholder-image-sq.png" class="img-responsive" /></a>
                </div>
                <div class="col-sm-3">
                    <a href="#" data-lightbox="img/placeholder-image.png" data-caption="Image description" data-gallery-id="gallery-1"><img src="img/placeholder-image-sq.png" class="img-responsive" /></a>
                </div>
                <div class="col-sm-3">
                    <a href="#" data-lightbox="img/placeholder-image.png" data-caption="Image description" data-gallery-id="gallery-1"><img src="img/placeholder-image-sq.png" class="img-responsive" /></a>
                </div>
                <div class="col-sm-3">
                    <a href="#" data-lightbox="img/placeholder-image.png" data-caption="Image description" data-gallery-id="gallery-1"><img src="img/placeholder-image-sq.png" class="img-responsive" /></a>
                </div>
            </div>
        </div>
    </div>
    <!-- bloc-3 END -->

app/views/gallery/new.html.erb
<!-- bloc-2 -->
<div class="bloc l-bloc bgc-white" id="bloc-2">
    <div class="container bloc-lg">
        <div class="row">
            <div class="col-sm-12">
                <%= form_for @photo, local: true, html: { multipart: true } do |f| %>
                    <div class="form-group">
                        <%= f.label :image, "Upload Image" %>
                        <%= f.file_field :image, class:"form-control-file", id:"upload_image" %>
                    </div
                <%= f.label :title, "Title", for:"upload_title" %>
                <p class="mg-lg">
                    <%= f.text_field :title, class:"form-control", id:"upload_title", placeholder:"Title" %>
                </p>
                <%= f.label :description, "Descripe", for:"Descripe" %>
                <p class="mg-lg">
                    <%= f.text_area :description, class:"form-control", rows:"5", id:"Descripe", placeholder:"Descripe" %>
                </p>
                <%= f.submit "Create", class:"btn btn-d btn-lg" %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<!-- bloc-2 END -->

app/views/home/index.html.erb
<!-- bloc-1 -->
<div class="bloc l-bloc bgc-white bloc-fill-screen" id="bloc-1">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="text-center hero-bloc-text">
                    發掘靈感
                </h1>
                <h3 class="text-center mg-lg hero-bloc-text-sub">
                    分享您獨一無二的世界
                </h3>
                <div class="text-center">
                    <% if current_user %>
                        <%= link_to  "藝廊", user_galleries_path(current_user), class: "btn-wire btn btn-xl"%>
                    <% else %>
                        <%= link_to "註冊", new_registration_path(:user), class: "btn-wire btn btn-xl" %>
                    <% end %>
                </div>
            </div>
        </div>

    </div>
    
    <div class="container fill-bloc-bottom-edge">
        <div class="row">
            <div class="col-sm-12">
            <a id="scroll-hero" class="blocs-hero-btn-dwn"><img src="https://png.icons8.com/ios/50/666666/circled-chevron-down-filled.png"></a>
            </div>
        </div>
    </div>
</div>

<!-- bloc-1 END -->
<div class="bloc l-bloc bgc-white">
    <div class="container bloc-lg" id="gallery_view">
        <%= render "galleries/gallery_view", galleries: @news, title: "最新" %>
    </div>
</div>

app/views/layouts/_nav.html.erb
<div class="container fill-bloc-top-edge">
    <nav class="navbar row">
        <div class="navbar-header">
            <%= link_to  "Inspiration", root_path, class: "navbar-brand"%>
                <button id="nav-toggle" type="button" class="ui-navbar-toggle navbar-toggle" data-toggle="collapse" data-target=".navbar-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
        </div>
        <div class="collapse navbar-collapse navbar-1">
            <ul class="site-navigation nav navbar-nav pull-right">
                <li>
                    <%= link_to  "首頁", root_path, class: "navbar-brand"%>
                </li>
                <% if current_user %>
                    <li>
                        <%= link_to  "藝廊", user_galleries_path(current_user) %>
                    </li>   
                    <li>
                        <%= link_to  "上傳", new_user_gallery_path(current_user) %>
                    </li>
                    <li>
                        <%= link_to "個人資料", edit_user_registration_path %>
                    </li>
                    <li>
                        <%= link_to "登出", destroy_user_session_path, method: "delete" %>
                    </li>
                    <% else %>
                        <li>
                            <%= link_to "登入", new_user_session_path %>
                        </li>
                        <li>
                            <%= link_to "註冊", new_registration_path(:user) %>
                        </li>
                <% end %>

            </ul>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
  <meta name="turbolinks-cache-control" content="no-preview">
  <title>Inspiration</title>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" type="image/png" href="favicon.png">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
  <!-- Main container -->
  <div class="page-container">
    <div class="bloc l-bloc bgc-white">
      <%= render "layouts/nav" %>
      <% if notice && notice.include?("ERROR") %>
        <%= "<div class='alert alert-danger alert-dismissible' role:'alert'>#{notice}</div>".html_safe %>
      <% elsif notice %>
        <%= "<div class='alert alert-info alert-dismissible' role:'alert'>#{notice}</div>".html_safe %>
      <% elsif alert %>
        <%= "<div class='alert alert-warning alert-dismissible' role:'alert'>#{alert}</div>".html_safe %>
      <% end %>
    </div>
    
    <%= yield %>
    <!-- ScrollToTop Button -->
    <a class="bloc-button btn btn-d scrollToTop" onclick="scrollToTarget('1')"><span class="fa fa-chevron-up"></span></a>
    <!-- ScrollToTop Button END-->
  </div>
  <!-- Main container END -->
</body>

</html>